// <auto-generated />
using GraphQLProject.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GraphQLProject.Migrations
{
    [DbContext(typeof(GraphQLDbContext))]
    [Migration("20251210165752_SeedMenusTable")]
    partial class SeedMenusTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GraphQLProject.Models.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.ToTable("Menus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A juicy burger with lettuce and cheese",
                            Name = "Class Burger",
                            Price = 8.9900000000000002
                        },
                        new
                        {
                            Id = 2,
                            Description = "Tomato, mozzarella, and basil Pizza",
                            Name = "Margherita Pizza",
                            Price = 10.5
                        },
                        new
                        {
                            Id = 3,
                            Description = "Fresh garden salad with grilled chicken",
                            Name = "Grilled Chicken Salad",
                            Price = 7.9500000000000002
                        },
                        new
                        {
                            Id = 4,
                            Description = "Creamy Alfredo sauce with fettuccine pasta",
                            Name = "Pasta Alfredo",
                            Price = 12.75
                        },
                        new
                        {
                            Id = 5,
                            Description = "Warm chocolate brownie with ice cream and fudge Pizza",
                            Name = "Chocolate Browie Sundae",
                            Price = 6.9900000000000002
                        },
                        new
                        {
                            Id = 6,
                            Description = "Delicious Pizza",
                            Name = "Pizza",
                            Price = 10.5
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
